### ISSUE TITLE
可以用宝塔的dock搭建嘛？

### ISSUE THREAD

**Issue by hereww** [tuangtalk/chatgpt-wecom#1]
问问

**Comment by tuangtalk** [comment]
可以的，不用docker也可以

**Comment by aismart** [comment]
怎么搭建

**Comment by tuangtalk** [comment]
md 有docker 部署教程，对于宝塔上的docker 也能用------------------------------------------------------------------

**Comment by hereww** [comment]
md？是啥网站？

**Comment by tuangtalk** [comment]
就是我首页的介绍

**Comment by hereww** [comment]
你好。我卡在宝塔挂载部分了我不知道-v /www/docker/config:/app/src/config    这条应该卸载哪里，无论我卸载哪里都是错误的。

**Comment by hereww** [comment]
Traceback (most recent call last):
  File "/app/src/bot.py", line 2, in 
    from request import Request
  File "/app/src/request.py", line 5, in 
    from receivewx.handle import Handle
  File "/app/src/receivewx/handle.py", line 10, in 
    with open("src/config/data.yml","r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'src/config/data.yml'

**Comment by hereww** [comment]
我在宝塔日志下提示这个。

**Comment by hereww** [comment]
openapi回调地址请求不通过
然后打开地址后提示 no data

**Comment by tuangtalk** [comment]
这个是找不到data.yml 你看着映射的对不对

**Comment by tuangtalk** [comment]
回调是填你的域名:端口/api，直接打开nodata是对的，回调不通过看看是不是你的data.yml 里面的参数填错了

**Comment by tuangtalk** [comment]
用这个测https://open.work.weixin.qq.com/wwopen/devtool/interface?doc_id=14961

**Comment by hereww** [comment]
> 这个是找不到data.yml 你看着映射的对不对

宝塔不是输入命令映射  对话框上面填的文件目录

**Comment by hereww** [comment]
现在打开API地址
提示not found
xinyan.huiran.shop

**Comment by hereww** [comment]
http://0.0.0.0:6364/
YuYueXin
创建新的访问对象 YuYueXin
'YuYueXin'
请联系管理员为你添加密钥
向chatgpt发送信息返回失败
'str' object has no attribute 'ask'
error
183.47.98.168:45572 - - [14/Feb/2023 15:15:05] "HTTP/1.1 POST /api" - 200 OK

**Comment by hereww** [comment]
大佬。提示这个什么原因？是不是得设置企业微信管理的账号？
另外我怎么才能把自建应用推送给微信好友？

**Comment by hereww** [comment]
大佬现在是自主自建应用可以用了。但是我如何挂到微信客服？或则企业微信群？

**Comment by tuangtalk** [comment]
在微信里是可以使用企业微信bot 的 你可以搜一下怎么使用，我记得就是登陆企业微信电脑端在企业设置里面找有个二维码，拿微信扫一下，就可以在微信使用企业微信bot

**Comment by hereww** [comment]
企业微信bot 不是自建应用，这么连到微信BOT？

**Comment by tuangtalk** [comment]
可以在微信里使用企业微信的，你可以谷歌一下。以前的issues我说过这个
