### ISSUE TITLE
群晖docker报错

### ISSUE THREAD

**Issue by Argon2024** [tuangtalk/chatgpt-wecom#11]
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-davinci-003/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa1c6f779a0>: Failed to establish a new connection: [Errno 111] Connection refused')))

**Comment by tuangtalk** [comment]
网络连接不上openai 建议填代理
