### ISSUE TITLE
后台日志限制已经收到回复 但是企业微信没有消息

### ISSUE THREAD

**Issue by Argon2024** [tuangtalk/chatgpt-wecom#12]
可信IP具体填什么地址 填群晖的公网IP吗

**Comment by tuangtalk** [comment]
群晖的公网ip会变的，所以说需要搭建一个稳定的代理，cash v2啥的都支持http代理

**Comment by Mr-KID-github** [comment]
我同样遇到这个问题了，请求解决办法
Forbidden{
  "error": {
    "message": "Your request to GET /dashboard/billing/credit_grants must be made with a session key (that is, it can only be made from the browser). You made it with the following key type: secret.",
    "type": "server_error",
    "param": null,
    "code": null
  }
}
