### ISSUE TITLE
可以添加access_token的方式吗？

### ISSUE THREAD

**Issue by lhlxx2010** [tuangtalk/chatgpt-wecom#14]

**Comment by tuangtalk** [comment]
可以有空马上就改

**Comment by lhlxx2010** [comment]
> 可以有空马上就改

感谢，昨晚我改了想测试下，卡在了dockfile上。构建完还没验证。改端口是不是在bot.py那边改一下就行？因为我docker跑着你的第一个版本。

**Comment by tuangtalk** [comment]
这个dockfile 不是我上传的，是有个老哥pull上来的，你可以直接去我的dockerhub然后下载0.12版镜像安装

**Comment by lhlxx2010** [comment]
> 这个dockfile 不是我上传的，是有个老哥pull上来的，你可以直接去我的dockerhub然后下载0.12版镜像安装

我知道，你的镜像是账户密码的，我刚好只有谷歌账号，用不了。我在你基础上改了个access token得版本。但dockerfile不太熟。

**Comment by tuangtalk** [comment]
我已经更新access token版本，access token有简便获得的办法吗，账户密码登录好像不行了，被阻断了

**Comment by tuangtalk** [comment]
xxx:6364端口这样设置

**Comment by lhlxx2010** [comment]
> 我已经更新access token版本，access token有简便获得的办法吗，账户密码登录好像不行了，被阻断了

这个项目可以自动刷新。https://github.com/acheong08/OpenAIAuth，前天刚更新过。

**Comment by tuangtalk** [comment]
我用的就是这个，我是说直接从网页获取access token ，可以了我已经写进文档了，chatgpt今天崩了，现在恢复了

**Comment by lhlxx2010** [comment]
> 我用的就是这个，我是说直接从网页获取access token ，可以了我已经写进文档了，chatgpt今天崩了，现在恢复了

不，你仔细看。他这个项目是分8个步骤自动获取access token得。不是他的v1，之前坏了，前天刚更新。

**Comment by tuangtalk** [comment]
现在我们这个项目用的就是这个

**Comment by tuangtalk** [comment]
这个用账户密码登陆用到的验证方式可以模拟账户密码登陆得到access token ，如果直接用access token 不用执行这个验证

**Comment by lhlxx2010** [comment]
> 这个用账户密码登陆用到的验证方式可以模拟账户密码登陆得到access token ，如果直接用access token 不用执行这个验证

哦哦，是我理解错了。因为我没有非谷歌的账户密码，没有翻账户密码工作流的源码。现在token得方法太短了。我昨晚就在你的基础上改了token，没看到你更新了。你现在啥逻辑，如果token过期，可以自动切原来的api吗？这样可以保证项目长期运行。否则8小时不维护就挂了。

**Comment by tuangtalk** [comment]
他们那个验证文件没有返回access token如果要做这个，可能要改他们的源码。你可以弄一下，还有就是我的access token十几天了都没过期 ，就是那个很长的token.

**Comment by lhlxx2010** [comment]
> 



> 他们那个验证文件没有返回access token如果要做这个，可能要改他们的源码。你可以弄一下，还有就是我的access token十几天了都没过期 ，就是那个很长的token.

这么牛逼的吗。我的咋很快挂了。🤔

**Comment by tuangtalk** [comment]
你看看你获取到的是哪个token access token 是可以长时间存在的，chatgpt 貌似又抽风了

**Comment by lhlxx2010** [comment]
> 你看看你获取到的是哪个token access token 是可以长时间存在的，chatgpt 貌似又抽风了

就是那个access token，可能跟账号有关，我换个账户测试看看。没办法，太火了，而且确实有用。我老婆用他写ppt，下午不能用，把我骂死了

**Comment by tuangtalk** [comment]
哈哈，直接登陆网页看看

**Comment by lhlxx2010** [comment]
> 哈哈，直接登陆网页看看

下午官网也挂了，api也挂了

**Comment by tuangtalk** [comment]
从昨天我就发现了有点抽风，今天挂了，现在还是不稳定

**Comment by tuangtalk** [comment]
eyJhbGciOiJSUzI1NiIs 就这样开头的token

**Comment by lhlxx2010** [comment]
> eyJhbGciOiJSUzI1NiIs 就这样开头的token

是的，我知道。

> eyJhbGciOiJSUzI1NiIs 就这样开头的token

https://github.com/rhaym-tech/AIKey

**Comment by lhlxx2010** [comment]
> eyJhbGciOiJSUzI1NiIs 就这样开头的token

https://github.com/rhaym-tech/AIKey
