### ISSUE TITLE
企业微信接收消息服务器配置

### ISSUE THREAD

**Issue by hugegedegege** [tuangtalk/chatgpt-wecom#15]
我部署到了服务器，根据教程先运行了bot.py返回一个IP   **http://0.X.0.X:63XX/**。然后填入到了接收消息服务器配置中，但是显示无法回调

**Comment by hugegedegege** [comment]
openapi回调地址请求不通过，这个是地址是运行的程序返回的，还是要自己去申请的呀

**Comment by hugegedegege** [comment]
我也是加了api，可是不得行的http://0.0.0.0:63XX/api ，这个url不能用

**Comment by tuangtalk** [comment]
可能是ssl的问题？我是挂了域名证书用的443端口你这种我没试过 你可以看一下返回值，你可以测测https://open.work.weixin.qq.com/wwopen/devtool/interface?doc_id=14961然后把返回值给我看

**Comment by hugegedegege** [comment]
我是部署在腾讯云上的，用docker跑起来后，返回http://0.0.0.0:63XX这个地址，我就复制http://0.0.0.0:63XX/api到企业微信url，显示网址有问题，我猜应该用域名才能用，给个ip网址是不是不行

**Comment by tuangtalk** [comment]
你看以前的issue 之前有人用ip 成功通过了回调

**Comment by hugegedegege** [comment]
调用接口	测试回调模式
请求地址	http://0.0.0.0:6364/api?msg_signature=0390a627a89a6569e5035e0dbdec22a2961239f9&timestamp=1677114161&nonce=zwe8783oin&echostr=dnGan%2FQC6Qo6F9SDNrDCteA3raK3rJ1dW4zBqKR6QolDAIhuwHmAI6uKihAOSkWGe5iHVtiR8rMgcyEnLlP7dw%3D%3D
返回状态	
request: 失败
返回结果

**Comment by tuangtalk** [comment]
你的ip 该不会是0.0.0.0吧？你这填错了啊对应的是vps 或者nas 的公网ip啊

**Comment by hugegedegege** [comment]
import web
from request import Request
#鎺ュ彛閰嶇疆
urls = (
    '/api', 'Request',
)
class MyApplication(web.application):
    def run(self, port=6364, *middleware):
        func = self.wsgifunc(*middleware)
        return web.httpserver.runsimple(func, ('0.0.0.0', port))
是不是这里0.0.0.0改成我的服务器IP地址就可以呀?

**Comment by tuangtalk** [comment]
这是报错问题吗，看不出来有什么错误啊
