### ISSUE TITLE
新版本只能发送出去 收不到回信

### ISSUE THREAD

**Issue by Argon2024** [tuangtalk/chatgpt-wecom#16]
[ wecom -> chatgpt ] 你好172.17.0.1:39842 - - [23/Feb/2023 06:47:27] "HTTP/1.1 POST /api" - 200 OK | stdout

**Comment by tuangtalk** [comment]
如果控制台可以收到，你的企业微信收不到，那么就是企业微信代理ip 那一部分设置有问题，你可以看看 默认代理优先级，data.yml 里的企业微信代理>docker创建时环境变量里的全局代理>vps ip

**Comment by Argon2024** [comment]
现在又出现 程序出错已经存在用户wxuser,但是对应的机器人实例不存在

**Comment by tuangtalk** [comment]
那是你和chatgpt 网络通信在第一次使用的时候出问题了，过两天我修一下，你可以//新对话来解决这个问题

**Comment by tuangtalk** [comment]
你是使用access token登录的吗

**Comment by Argon2024** [comment]
是的 我试了&nbsp;

这个也不能返回消息



&nbsp;


晴天
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 晚上11:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuangtalk/chatgpt-wecom] 新版本只能发送出去 收不到回信 (Issue #16)






你是使用访问令牌登录的吗
—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by tuangtalk** [comment]
企业微信不能收到信息应该是可信代理配置有问题
