### ISSUE TITLE
GBT3.5 API来了，求更

### ISSUE THREAD

**Issue by lhlxx2010** [tuangtalk/chatgpt-wecom#17]

**Comment by tuangtalk** [comment]
马上就换，现在想着是有没有必要保留旧的了

**Comment by Rwindest168888** [comment]
搞吧，大佬，API的稳定，网页版用access_token不太稳

**Comment by lhlxx2010** [comment]
> 马上就换，现在想着是有没有必要保留旧的了

可以留个分支，但其实没必要了

**Comment by tongtong-hong** [comment]
> > 马上就换，现在想着是有没有必要保留旧的了
> 
> 可以留个分支，但其实没必要了

同意，防止以后收费变很贵依旧只能网页

**Comment by tongtong-hong** [comment]
> > 马上就换，现在想着是有没有必要保留旧的了
> 
> 可以留个分支，但其实没必要了

同意预留分支或者加tag，防止以后收费很贵

**Comment by tuangtalk** [comment]
加了tag，收费很贵我还会改回去哈哈
