### ISSUE TITLE
能否留个联系方式？

### ISSUE THREAD

**Issue by Justchatgpt** [tuangtalk/chatgpt-wecom#18]
我这里有openapi，包含18美刀的

**Comment by tuangtalk** [comment]
不太会搭建吗，还是什么

**Comment by Justchatgpt** [comment]
> 不太会搭建吗，还是什么

不是的，就是大家需要的话，我可以提供.价格优惠

**Comment by tuangtalk** [comment]
....我没有群，就是一个人玩，然后把代码发上来，不好意思啊帮不到你，你可以去一些有群的地方看看

**Comment by Justchatgpt** [comment]
> ....我没有群，就是一个人玩，然后把代码发上来，不好意思啊帮不到你，你可以去一些有群的地方看看

好的大佬，感谢你分享的项目，已经star
