### ISSUE TITLE
可不可以离开docker运行

### ISSUE THREAD

**Issue by gongxianhui0** [tuangtalk/chatgpt-wecom#2]
我有点小白，不想跑在家里想直接跑在VPS里，能不能求作者改成python窗口或者计划任务运行？好人一生平安，如果可能谢谢了。

**Comment by tuangtalk** [comment]
你直接把源码下载下来，在目录里创建config文件夹，在config文件夹下配置好data.yml，最后在命令窗口运行bot.py 就可以了

**Comment by tuangtalk** [comment]
记得下载requirements.txt里面指定版本的包
