### ISSUE TITLE
推送不出来消息

### ISSUE THREAD

**Issue by jl-dior** [tuangtalk/chatgpt-wecom#20]
![image](https://user-images.githubusercontent.com/23095378/222886219-a2aa99b7-0997-401d-84c7-4f3656baac65.png)
后台提示可以正常推送。

**Comment by tuangtalk** [comment]
搭建环境是什么，这是企业微信可信ip的问题

**Comment by jl-dior** [comment]
就是 vps的。服务器可以正常收到消息。可信ip也配置了，

**Comment by tuangtalk** [comment]
如果是才配置的要等几分钟，vps部署的config.yml里的weixinproxy那一行记得删掉或者留空，然后重启，可信ip填vps的ip

**Comment by jl-dior** [comment]
可以了，谢谢大佬
