### ISSUE TITLE
请教一下上下文的实现

### ISSUE THREAD

**Issue by lhlxx2010** [tuangtalk/chatgpt-wecom#21]
哈咯，我看了下源码，V3这个版本是用什么来实现上下文的？我在我自己的脚本内还是用对话历史来实现似乎没问题，但开销比较大。然后来你这边看，好像也没看到什么相关的代码。。

**Comment by tuangtalk** [comment]
chatgpt-wecom/src/chatgptmain/judgeuser.py 在这里做了一个判断，你可以看一下

**Comment by lhlxx2010** [comment]
> chatgpt-wecom/src/chatgptmain/judgeuser.py 在这里做了一个判断，你可以看一下

我意思是给到api接口的时候，是需要上下文一起带过去吗？还是用什么来判断？我看到你在revChatGPT的代码里也只是用response=chatbot.ask(question)，似乎也没带历史，handle中把message_list相关的都注释掉了。所以是不是新的api不需要带历史对话过去了？那用什么判断本次对话的上下文呢？

**Comment by Angusvencent** [comment]
data.yml Wrong paramemapping values are not allowed here
  in "<unicode string>", line 3, column 12:
        Api_key: 
yml格式一直报错是咋回事呀

**Comment by tuangtalk** [comment]
> data.yml Wrong paramemapping values are not allowed here in "", line 3, column 12: Api_key: yml格式一直报错是咋回事呀

使用这个校验下格式，注意不要泄露关键信息：https://www.bejson.com/validators/yaml_editor/

**Comment by tuangtalk** [comment]
> 使用这个校验下格式，注意不要泄

yml 的空格不能用回车打只能敲回车键

**Comment by tuangtalk** [comment]
> > chatgpt-wecom/src/chatgptmain/judgeuser.py 在这里做了一个判断，你可以看一下
> 
> 我意思是给到api接口的时候，是需要上下文一起带过去吗？还是用什么来判断？我看到你在revChatGPT的代码里也只是用response=chatbot.ask(question)，似乎也没带历史，handle中把message_list相关的都注释掉了。所以是不是新的api不需要带历史对话过去了？那用什么判断本次对话的上下文呢？

就按照我这样，你试一下就知道了，我在openai的api文档里看到过

**Comment by Angusvencent** [comment]
> 

谢谢大佬， 已解决！

**Comment by tuangtalk** [comment]
好的好的，那我close
