### ISSUE TITLE
连不上openai

### ISSUE THREAD

**Issue by Angusvencent** [tuangtalk/chatgpt-wecom#23]
报错如下：
requests.exceptionsraise ConnectTimeout(e, request=request).
ConnectTimeout: requests.exceptionsHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb444003370>, 'Connection to api.openai.com timed out. (connect timeout=None)')).
ConnectTimeout: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /dashboard/billing/credit_grants (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb443e69e10>, 'Connection to api.openai.com timed out. (connect timeout=None)'))

**Comment by tuangtalk** [comment]
vps 部署还是什么环境

**Comment by Angusvencent** [comment]
linux系统的云服务器

**Comment by tuangtalk** [comment]
直接可以访问openai api可以吗
是一直不行还是什么

**Comment by Angusvencent** [comment]
是需要海外服务器吗？

**Comment by tuangtalk** [comment]
命令行 直接curl一下

**Comment by tuangtalk** [comment]
> 是需要海外服务器吗？

国内服务器需要代理，国内访问不了openai，或者你也可以修改host

**Comment by tuangtalk** [comment]
指定api.openai.com的host ip为52.152.96.252

**Comment by Angusvencent** [comment]
好的，谢谢大佬，我去试试

**Comment by tuangtalk** [comment]
> 是需要海外服务器吗？

指定api.openai.com的host ip为52.152.96.252应该也可以解决国内服务无法访问的问题，我没试过应该可以的

**Comment by tuangtalk** [comment]
指定好ping 一下能通应该就可以具体我也没试过
