### ISSUE TITLE
自建 http 代理(服务器部署用户不需要) 是指什么意思？ 是openai的接口被封吗，需要建一个代理吗

### ISSUE THREAD

**Issue by alphanlp** [tuangtalk/chatgpt-wecom#24]

**Comment by tuangtalk** [comment]
如果你是国内环境部署的，会出现两个问题1.openai api无法连接，2. 如果是家庭宽带动态公网会导致微信推送无法添加可信ip，因此需要一个proxy也就是梯子🪜来解决我说的这两条的网络问题。对于国外环境的话则没有上面两点问题，所以说不需要配置代理
