### ISSUE TITLE
关于接收消息服务器配置

### ISSUE THREAD

**Issue by JustinQiuck** [tuangtalk/chatgpt-wecom#25]
企微后台，关于接收消息服务器配置是需要域名来配置的，不能设置IP，域名的映射该怎么搞？

**Comment by tuangtalk** [comment]
不需要域名吧应该

**Comment by tuangtalk** [comment]
设置完api接口回调就可以设置可信ip了

**Comment by JustinQiuck** [comment]
已经解决。不知道为何，我这边需要域名。我做了一个反向代理到IP+端口。然后域名/api就可以了。

tuangtalk ***@***.***> 于2023年3月8日周三 17:47写道：
