### ISSUE TITLE
为每一个用户配置一个key比较麻烦，可否配置一个通用的？

### ISSUE THREAD

**Issue by CitrusFlavored** [tuangtalk/chatgpt-wecom#27]
如题，为每一个微信用户配置一个key比较麻烦，可否配置一个通用的？

**Comment by tuangtalk** [comment]
多个用户一个key，再用gpt3的时候我以前试过会有一些莫名其妙的问题，感觉用的人多了回答问题特别呆，所以就没用了。现在不知道好了没
