### ISSUE TITLE
ModuleNotFoundError: No module named 'revChatGPT'

### ISSUE THREAD

**Issue by HuntLee770090834** [tuangtalk/chatgpt-wecom#28]
为何在无法本地运行

**Comment by tuangtalk** [comment]
你要先执行 pip install -r requirements.txt 去安装 依赖包，建议你直接docker部署不用配置环境

**Comment by HuntLee770090834** [comment]
> 你要先执行 pip install -r requirements.txt 去安装 依赖包，建议你直接docker部署不用配置环境

  好的，我试试，docker的话我不太会使用，而且我没看懂‘挂载的 -v /你自己创建的文件夹/config:/app/src/config’ 这个怎么使用

**Comment by tuangtalk** [comment]
那是docker用的 你直接把src  config 文件夹下的data.yml.sample重命名成data.yml就可以啦，如果后面配置里面的内容的时候格式提示有问题，你就搜一下yml 格式校验

**Comment by HuntLee770090834** [comment]
> 



> 那是docker用的 你直接把src config 文件夹下的data.yml.sample重命名成data.yml就可以啦，如果后面配置里面的内容的时候格式提示有问题，你就搜一下yml 格式校验 Message ID: ***@***.***>

  好的，谢谢

**Comment by HuntLee770090834** [comment]
大佬，我在使用docker部署时遇到了一些问题，不知道是否可以获取到你的联系方式？

**Comment by HuntLee770090834** [comment]
> 那是docker用的你直接把src config文件夹下的data.yml.sample重命名成data.yml就可以啦，如果后面配置里面的内容的时候格式提示有问题，你就搜一下搜下yml消息ID：***@***.***>

大佬，我在使用docker部分时遇到了一些问题，不知道是否可以获取到你的联系方式？【苦笑】

**Comment by tuangtalk** [comment]
你可以贴到这里 我来给你看看

**Comment by HuntLee770090834** [comment]
![image](https://user-images.githubusercontent.com/57931508/225581767-01242e19-f43d-466c-9571-b2f67abfdf50.png)
就是我现在挂载配置文件后无法给容器映射端口

**Comment by HuntLee770090834** [comment]
> ![image](https://user-images.githubusercontent.com/57931508/225581767-01242e19-f43d-466c-9571-b2f67abfdf50.png) 就是我现在挂载配置文件后无法给容器映射端口

这是不是就意味着我无法访问ip:6364/balance？

**Comment by tuangtalk** [comment]
![image](https://user-images.githubusercontent.com/122268051/225582384-fcf1828b-c6f8-4a63-9977-8ad4bc51af28.png)，你这个配置文件不是提示未找到吗？ 没办法给端口是因为已经存在映像了，你删了镜像就可以了，
你不会的话可以直接安装```宝塔```或者```portainer```，用里可视化docker面板
ip:6364/balance只是用来查询key的额度的，你想要接入企业微信需要的是在企业微信里进行会调用验证```ip:6364/api```我教程里面写的都有

**Comment by tuangtalk** [comment]
https://colobu.com/2018/05/15/Stop-and-remove-all-docker-containers-and-images/

**Comment by HuntLee770090834** [comment]
> 
  这是因为我之前 是直接使用的 docker -v   我应该使用docker run -v  那我第二个容器是否代表已经成功了呀？

**Comment by HuntLee770090834** [comment]
> 

我访问ip:6364/balance 是想验证一下我程序是否启动成功【苦笑】

**Comment by tuangtalk** [comment]
> > 
> 
> 这是因为我之前 是直接使用的 docker -v 我应该使用docker run -v 那我第二个容器是否代表已经成功了呀？
是成功了，然后看一下docker 日志

**Comment by tuangtalk** [comment]
https://blog.csdn.net/xiejunna/article/details/86222859

**Comment by tuangtalk** [comment]
没有成功 你现在的问题是你没有映射配置文件 你干脆用可视化面板操作呗

**Comment by HuntLee770090834** [comment]
> 没有成功 你现在的问题是你没有映射配置文件 你干脆用可视化面板操作呗

![image](https://user-images.githubusercontent.com/57931508/225588970-e40211fe-e315-4062-838c-b9d2b057720b.png)
 我想再试试😭，现在这样是成功了么？可是我仍然无法访问查看额度的页面（服务器端口已打开）

**Comment by tuangtalk** [comment]
对了 这就没问题了 你安全组端口记得放行 然后访问ip:6364/balance 然后查看docker日志https://www.jianshu.com/p/1eb1d1d3f25e，看看日志提示什么（yml里要配置BALANCE:
  CKBALANCE: true）

**Comment by tuangtalk** [comment]
怎么样了

**Comment by HuntLee770090834** [comment]
> 怎么样了

![image](https://user-images.githubusercontent.com/57931508/225597006-2702c1c2-cca9-4400-b81d-58cdbee6783a.png)
  正在研究这两个如何获取😂

**Comment by HuntLee770090834** [comment]
> > 怎么样了
> 
> ![image](https://user-images.githubusercontent.com/57931508/225597006-2702c1c2-cca9-4400-b81d-58cdbee6783a.png) 正在研究这两个如何获取😂

  我找到了，但是提示我openai的回调请求不通过，我是还需要再配置梯子吧？

**Comment by tuangtalk** [comment]
你把data.yml 需要的内容  填进去  然后```重启容器``` 在试以下 没问题回调应该就过了

**Comment by tuangtalk** [comment]
不是国内的vps就不需要梯子

**Comment by HuntLee770090834** [comment]
> 不是国内的vps就不需要梯子

 回调已经过了，但是目前我看日志是Connection to api.openai.com timed out  我的服务器是腾讯云，国内的实例，  大佬你有推荐的服务器上的梯子么？

**Comment by tuangtalk** [comment]
这样的话就需要在docker 部署的时候加上http代理对你来说又是灾难，，，
还有一个暂时的方法就是指定host 设置host api.openai.com 52.152.96.252 这样就不用配置代理了，你直接搜centos host 修改

**Comment by HuntLee770090834** [comment]
> 



> docker 部署的时候加上http代理

![image](https://user-images.githubusercontent.com/57931508/226075781-1fce85b3-f2ed-452b-84b5-980c0ffc995b.png)
在修改host后，启动程序就一直卡在这里😭

**Comment by tuangtalk** [comment]
回调接口不是过了吗，你用企业微信用户发个信息看看再日志

**Comment by HuntLee770090834** [comment]
> 回调接口不是过了吗，你用企业微信用户发个信息看看再日志

 对，之前是在企微发送消息可以在日志中查看到消息内容， 但是现在就一直卡在 http://0.0.0.0:6364 这里

**Comment by tuangtalk** [comment]
你host怎么设置的啊，实在不行就把docker容器删了重建啊，

**Comment by HuntLee770090834** [comment]
> 



> 你host怎么设置的啊，实在不行就把docker容器删了重建啊，

 host 是 52.152.96.252  api.openai.com  这样设置的     然后我把它删了，重新新建容器也是一直卡在这里😭😭😭

**Comment by tuangtalk** [comment]
你把host删掉会恢复嘛

**Comment by HuntLee770090834** [comment]
> 你把host删掉会恢复嘛

我把host中新加的配置删除后也还是如此

**Comment by tuangtalk** [comment]
那就不是host的问题了啊，你把容器删了，然后把镜像也删了，重新拉一下镜像看看

**Comment by tuangtalk** [comment]
你再重新测试下回调和balance 看看是不是安全组端口的问题

**Comment by HuntLee770090834** [comment]
> 你再重新测试下回调和balance 看看是不是安全组端口的问题

安全组端口我打开了，确实是回调的问题  ，显示openai回调失败

**Comment by tuangtalk** [comment]
是不是创建的时候端口变了 查看下docker现在占用的端口是啥

**Comment by HuntLee770090834** [comment]
> 是不是创建的时候端口变了 查看下docker现在占用的端口是啥

![image](https://user-images.githubusercontent.com/57931508/226078360-80d2cc4d-c7a3-4083-9d09-2cac859989b4.png)
不知道是什么原因造成的了，我又重新生成了token和EncodingAESKey等 重启也是这样😭😭😭😭

**Comment by tuangtalk** [comment]
这……
究竟是什么问题……

**Comment by tuangtalk** [comment]
https://open.work.weixin.qq.com/wwopen/devtool/interface?doc_id=14961 拿这个测测接口回调

**Comment by HuntLee770090834** [comment]
> https://open.work.weixin.qq.com/wwopen/devtool/interface?doc_id=14961 拿这个测测接口回调

![image](https://user-images.githubusercontent.com/57931508/226083712-9c4b72bb-f6ad-4f07-a984-912a28775162.png)
没有结果返回😿

**Comment by tuangtalk** [comment]
你把回文随便输入几个字 看看反回结果，或者你改一个你确定是通的端口，比如创建的时候-p xxx:6364 ,```xxxx```是可以自定义的端口号

**Comment by HuntLee770090834** [comment]
> 你把回文随便输入几个字 看看反回结果，或者你改一个你确定是通的端口，比如创建的时候-p xxx:6364 ,`xxxx`是可以自定义的端口号

-p 6366:6364    这两个值 无论我修改哪一个  或者都修改  都是始终输出  http://0.0.0.0:6364/

**Comment by tuangtalk** [comment]
不影响的，后面那个不能修改不然会打不开网页的，那是容器端口，如果你修改了-p xxxx:6364 ，然后你访问的端口就是xxxx，后面的6364不要改！！！这个输输出 http://0.0.0.0:6364/不要管

**Comment by tuangtalk** [comment]
解决了吗

**Comment by HuntLee770090834** [comment]
> 解决了吗

没有，不知道是什么原因😂

**Comment by tuangtalk** [comment]
😂

**Comment by HuntLee770090834** [comment]
> 解决了吗

 解决了  解决了😁😁😁😁   我使用service docker restart重启docker服务就好了，然后每次修改host 都需要重启，不然就会卡在那里，  不过我发现通过修改host貌似没有用，一直连接超时，我现在打算去研究研究Linux下的梯子

**Comment by tuangtalk** [comment]
haha 好的好的

**Comment by HuntLee770090834** [comment]
> haha 好的好的

 终于弄完了，现在可以在企微中正常对话了，非常感谢大佬这几天的支持， 如果方便的话 我想V大佬喝杯下午茶🤭🤭

**Comment by tuangtalk** [comment]
😬客气了，打赏就不用啦，可以用就好，哈哈
