### ISSUE TITLE
牛啊，但是可以出一个清空上下文的指令吗？

### ISSUE THREAD

**Issue by lhlxx2010** [tuangtalk/chatgpt-wecom#6]
花了10分钟搭建了一下，很顺畅很好用。但是可以出一个清空上下文的指令吗？否则感觉怪怪的聊天，谢谢老大。

另外，这个api的智商确实不太够，如果能有账户密码的就好了，当然这个有点困难。。。再次感谢！

**Comment by tuangtalk** [comment]
好的，有时间我弄一下

**Comment by lhlxx2010** [comment]
> 好的，有时间我弄一下

acheong08那个V1版本用账户密码的跑通了，把他替换到你这套里容易吗？

**Comment by tuangtalk** [comment]
容易，有空我弄一下，你也可以自己弄一下
