### ISSUE TITLE
后台显示看到gpt回复了，但是企业微信收不到呢？

### ISSUE THREAD

**Issue by KevinJun2017** [tuangtalk/chatgpt-wecom#8]
如题
<img width="521" alt="截屏2023-02-14 23 49 33" src="https://user-images.githubusercontent.com/34047430/218788132-d67e1988-49c2-45e7-8be0-ad8a6df32f50.png">

**Comment by tuangtalk** [comment]
企业微信可信ip 没配置好

**Comment by Argon2024** [comment]
代理那一块看得不是很懂 可以详细讲一下吗

**Comment by Argon2024** [comment]
那我搭代理是不是还需要一台VPS 我有一台甲骨文




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月18日(星期六) 上午9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuangtalk/chatgpt-wecom] 后台显示看到gpt回复了，但是企业微信收不到呢？ (Issue #8)

**Comment by tuangtalk** [comment]
理论是这，你可以谷歌一下如何搭建http代理

**Comment by Argon2024** [comment]
好的，谢谢。






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月18日(星期六) 上午9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tuangtalk/chatgpt-wecom] 后台显示看到gpt回复了，但是企业微信收不到呢？ (Issue #8)





 理论是这，你可以谷歌一下如何搭建http代理
