### ISSUE TITLE
网上找了好多方法，现加不了可信任业微信可信域名，和IP，有办法的大佬，说一下，谢谢

### ISSUE THREAD

**Issue by Rwindest168888** [tuangtalk/chatgpt-wecom#9]
网上找了好多方法，现加不了可信任业微信可信域名，和IP，有办法的大佬，说一下，谢谢

**Comment by tuangtalk** [comment]
你是用什么搭建的，用vps 的话自己的在企业微信可信ip 里面添加vps 的ip 就可以

**Comment by Rwindest168888** [comment]
> 
> 你是用什么搭建的，用vps 的话自己的在企业微信可信ip 里面添加vps 的ip 就可以
> 
> 

我是自己的云服务上部署，是添加可信ip那，必须先增加可以信任域名，才能下面加ip，不知是不是我操作错了，但可信任域名死活没办法增加

**Comment by tuangtalk** [comment]
不用增加可信任域名，你只要通过企业微信接收消息api回调之后就可以添加可信ip

**Comment by Rwindest168888** [comment]
> 不用增加可信任域名，你只要通过企业微信接收消息api回调之后就可以添加可信ip

好的，谢谢，有没有data.yml 文件上传看下，谢谢，现老提示格式不对，

**Comment by Rwindest168888** [comment]
搞了一个晚上可以了，谢谢了

**Comment by hugegedegege** [comment]
> 网上找了好多方法，现加不了可信任业微信可信域名，和IP，有办法的大佬，说一下，谢谢
大哥，可否加个微信指导一下

**Comment by tuangtalk** [comment]
不用添加可信任域名，你只要通红过了https://yourdomain.com/api 回调，就可以添加docker设置的代理ip为企业微信可信任ip

**Comment by tuangtalk** [comment]
你要看看你docker设置的企业微信代理对应的ip 为多少。如果没设置企业微信代理，那么就是环境变量的全局，如果没有全局代理，那么就是vps 的ip
